version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root
    ports:
      - 3306:3306
    networks:
      - my_network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my_network

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8888:8888
    networks:
      - my_network

  registry:
    container_name: registry
    build:
      context: ./registry
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8761:8761
    networks:
      - my_network

  catalog:
    container_name: catalog
    build:
      context: ./catalog
      dockerfile: Dockerfile
    depends_on:
      - catalog-build
      - config-server
      - zipkin
      - registry
    ports:
      - 8080:8080
    networks:
      - my_network
    links:
      - config-server
      - registry
      - zipkin
    restart: on-failure

  catalog-build:
    image: maven:3.8.3-openjdk-11
    build:
      context: ./catalog
      dockerfile: Dockerfile
    command: mvn clean package
    volumes:
      - ./catalog:/app

networks:
  my_network:
