spring:
  config:
    import: http://config-server:8888/db-mysql-docker.yml

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/Shop?createDatabaseIfNotExist=true&esessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#     username: root
#     password: Root

#   jpa:
#     generate-ddl: true
#     hibernate:
#       ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
