server:
  port: 9999

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://CATALOG
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: rating
          uri: lb://RATING
          predicates:
            - Path=/rating/**
          filters:
            - StripPrefix=1
        - id: purchase
          uri: lb://PURCHASE
          predicates:
            - Path=/purchase/**
          filters:
            - StripPrefix=1
