server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://CATALOG 
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: rating
          uri: lb://RATING
          predicates:
            - Path=/rating/**
          filters:
            - StripPrefix=1

        - id: purchase
          uri: lb://PURCHASE
          predicates:
            - Path=/purchase/**
          filters:
            - StripPrefix=1

