# Specifica l'URI del repository Git che contiene i file di configurazione

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcomoser01/spring-config
          # la validazione SSL verrà saltata
          skipSslValidation: true
